/**
 * OpenNutri Service Worker
 * 
 * Provides offline support for:
 * - Static assets (JS, CSS, WASM)
 * - API responses (with network-first fallback)
 * - ML models (Transformers.js)
 * - Food images (cached after upload)
 * 
 * Task 5.2: Robust offline support with WASM ML models
 */

/// <reference lib="webworker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

// Declare the Webpack manifest injection
declare let self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: any[];
};

// Precache all static assets generated by Next.js
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// ============================================
// Cache Names
// ============================================
const STATIC_CACHE = 'opennutri-static-v1';
const API_CACHE = 'opennutri-api-v1';
const USDA_CACHE = 'opennutri-usda-v1';
const ML_MODELS_CACHE = 'opennutri-ml-models-v1';
const IMAGES_CACHE = 'opennutri-images-v1';

// ============================================
// Background Sync for Offline Actions
// ============================================
const bgSyncPlugin = new BackgroundSyncPlugin('opennutri-queue', {
  maxRetentionTime: 24 * 60, // 24 hours in minutes
});

// ============================================
// Static Assets (JS, CSS, WASM)
// ============================================
registerRoute(
  ({ request, url }) => {
    return (
      request.destination === 'script' ||
      request.destination === 'style' ||
      url.pathname.endsWith('.wasm') ||
      url.pathname.endsWith('.worker.js')
    );
  },
  new CacheFirst({
    cacheName: STATIC_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// ============================================
// API Routes (Network First with Offline Fallback)
// ============================================
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: API_CACHE,
    networkTimeoutSeconds: 10,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
      bgSyncPlugin,
    ],
  })
);

// ============================================
// USDA API (Stale While Revalidate)
// ============================================
registerRoute(
  ({ url }) => url.hostname === 'api.nal.usda.gov',
  new StaleWhileRevalidate({
    cacheName: USDA_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
      }),
    ],
  })
);

// ============================================
// ML Models (Hugging Face / Transformers.js)
// Task 4.2: Force immutable headers for large model files
// ============================================
registerRoute(
  ({ url }) =>
    url.hostname.includes('huggingface.co') ||
    url.hostname.includes('cdn.jsdelivr.net') ||
    url.pathname.includes('transformers') ||
    url.pathname.includes('onnx'),
  async ({ request }) => {
    const cache = await caches.open(ML_MODELS_CACHE);
    const cachedResponse = await cache.match(request);
    
    if (cachedResponse) {
      return cachedResponse;
    }

    try {
      const response = await fetch(request);
      
      // Only cache successful responses
      if (response.status === 200) {
        // Clone the response to modify headers
        const headers = new Headers(response.headers);
        headers.set('Cache-Control', 'public, max-age=31536000, immutable');
        
        const responseToCache = new Response(response.body, {
          status: response.status,
          statusText: response.statusText,
          headers,
        });

        await cache.put(request, responseToCache.clone());
        return responseToCache;
      }
      
      return response;
    } catch (error) {
      console.error('ML Model fetch failed:', error);
      return fetch(request); // Fallback to network
    }
  }
);

// ============================================
// Images (Cache First)
// ============================================
registerRoute(
  ({ request, url }) => {
    return (
      request.destination === 'image' ||
      url.pathname.endsWith('.png') ||
      url.pathname.endsWith('.jpg') ||
      url.pathname.endsWith('.jpeg') ||
      url.pathname.endsWith('.gif') ||
      url.pathname.endsWith('.svg') ||
      url.pathname.endsWith('.webp')
    );
  },
  new CacheFirst({
    cacheName: IMAGES_CACHE,
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// ============================================
// Offline Fallback for Navigation
// ============================================
registerRoute(
  ({ request, url }) => {
    return request.mode === 'navigate';
  },
  new NetworkFirst({
    cacheName: 'pages-cache',
    networkTimeoutSeconds: 5,
  })
);

// ============================================
// Push Notifications (for coaching insights)
// ============================================
self.addEventListener('push', (event) => {
  const data = event.data?.json() ?? {};
  const title = data.title ?? 'OpenNutri';
  const options = {
    body: data.body ?? 'New coaching insight available',
    icon: '/icon-192x192.png',
    badge: '/icon-72x72.png',
    data: data.data,
    tag: data.tag ?? 'default',
    actions: data.actions ?? [], // Support actionable notifications (e.g., "One-Tap Update")
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

// ============================================
// Notification Click Handler
// ============================================
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  // Task 5.1: Actionable Push Notifications
  // Handle specific actions (like "UPDATE_TARGET")
  let urlToOpen = event.notification.data?.url ?? '/dashboard';
  
  if (event.action === 'view_insight') {
    urlToOpen = `/dashboard?insight=${event.notification.data?.insightId}`;
  } else if (event.action === 'apply_update') {
    urlToOpen = `/dashboard?action=apply&insight=${event.notification.data?.insightId}`;
  }

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        // Check if there's already a window open
        for (const client of windowClients) {
          if (client.url === urlToOpen && 'focus' in client) {
            return client.focus();
          }
        }
        // Open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      })
  );
});

// ============================================
// Message Handler (for cache management)
// ============================================
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  if (event.data && event.data.type === 'CLEAR_CACHES') {
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames
            .filter((name) => name.startsWith('opennutri-'))
            .map((name) => caches.delete(name))
        );
      })
    );
  }

  if (event.data && event.data.type === 'CACHE_MODELS') {
    // Pre-cache ML models on first install
    event.waitUntil(
      caches.open(ML_MODELS_CACHE).then(async (cache) => {
        const modelUrls = [
          // MobileNet v2 (fallback)
          'https://huggingface.co/onnx-community/mobilenetv2-1.0-224/resolve/main/model.onnx',
          // all-MiniLM-L6-v2 (embeddings)
          'https://huggingface.co/xenova/all-MiniLM-L6-v2/resolve/main/onnx/model.onnx',
        ];

        try {
          await cache.addAll(modelUrls);
          console.log('ML models pre-cached successfully');
        } catch (error) {
          console.error('Failed to pre-cache ML models:', error);
        }
      })
    );
  }
});

// ============================================
// Install Event - Pre-cache critical assets
// ============================================
self.addEventListener('install', (event) => {
  console.log('[OpenNutri SW] Installing service worker...');

  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) => {
      return cache.addAll([
        '/',
        '/offline',
        '/manifest.json',
        '/icon-192x192.png',
        '/icon-72x72.png',
      ]);
    })
  );

  self.skipWaiting();
});

// ============================================
// Activate Event - Cleanup old caches
// ============================================
self.addEventListener('activate', (event) => {
  console.log('[OpenNutri SW] Activating service worker...');

  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames
          .filter((name) => {
            // Delete old cache versions
            return (
              name.startsWith('opennutri-') &&
              name !== STATIC_CACHE &&
              name !== API_CACHE &&
              name !== USDA_CACHE &&
              name !== ML_MODELS_CACHE &&
              name !== IMAGES_CACHE
            );
          })
          .map((name) => {
            console.log('[OpenNutri SW] Deleting old cache:', name);
            return caches.delete(name);
          })
      );
    })
  );

  self.clients.claim();
});

// Export TypeScript type
export type {};
